# Generated by Django 5.2.3 on 2025-07-06 17:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
        ('textprocessor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_used', models.CharField(help_text='Topic from file used to generate quiz', max_length=200)),
                ('generation_method', models.CharField(choices=[('full_text', 'Full Document'), ('topic_section', 'Specific Topic Section'), ('summary', 'Document Summary')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file_size',
            field=models.PositiveIntegerField(default=0, help_text='File size in bytes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='original_filename',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='processed_topics',
            field=models.JSONField(blank=True, help_text='AI-extracted topics and sections', null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='quizzes_generated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Processing'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'docx', 'pptx'])]),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF Document'), ('txt', 'Text File'), ('docx', 'Word Document'), ('pptx', 'PowerPoint')], max_length=10),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional processing metadata', null=True),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['user', 'status'], name='textprocess_user_id_17adf1_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['uploaded_at'], name='textprocess_uploade_b2b7ca_idx'),
        ),
        migrations.AddField(
            model_name='generatedquiz',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz'),
        ),
        migrations.AddField(
            model_name='generatedquiz',
            name='uploaded_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_quizzes', to='textprocessor.uploadedfile'),
        ),
    ]
