# Generated by Django 5.2.3 on 2025-07-07 04:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_dailychallenge_leaderboard_userprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquizattempt',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
